### PR TITLE
Update framework-artik-sdk to version 1.2.x

### PR DESCRIPTION
**Pull request by glemercier**
New version of the ARTIK SDK has been released, making it available in framework-artik-sdk. Full API documentation available here: https://developer.artik.io/documentation/api/

### CODE REVIEW

**Comment by glemercier** [comment]
ARTIK SDK 1.3 is now out therefore I need to update this PR. Does it make more sense to let the system pick the most recent version of the framework unless stated otherwise by the application configuration (like this [patch](https://github.com/glemercier/platform-linux_arm/commit/9837286a842cd61b7165a018d4c92601e0b231dc) would do) or is it better to always bind the framework to a specific package version?
In the latter case would it be better for me to rename the package version from "1.3.0" to "1.130" as done with the wiringPi framework?
Let me know what is the best way to proceed.

**Comment by ivankravets** [comment]
How about `"version": "*"`? Any versions from your registry?

**Comment by ivankravets** [comment]
Thanks! I changed it to `*`.

**Comment by glemercier** [comment]
Great, thanks a lot!

**Comment by ivankravets** [comment]
Excuse me for the late response. I missed that PR :(

**Pull request closed without merging**
