### PR TITLE
Use external package for ARTIK SDK framework instead of relying on system packages.

### PR DESCRIPTION
**Pull request by glemercier**

### CODE REVIEW

**Comment by glemercier** [comment]
Package is up and ready on our repo, online installation yet to be tested

**Comment by ivankravets** [comment]
Thanks! Please ping me when I should make a new release of dev.platform.

**Comment by ivankravets** [comment]
Opsss. The manifest is broken http://repo.artik.cloud/artik/bin/pub/platformio/manifest.json

You need to use DICT instead ARRAY for key-pair values. Please check your manifest with https://jsonformatter.curiousconcept.com

It should be 
```json
{  
  "framework-artik-sdk":[  
    {  
      "sha1":"739a05dd52ed5eee5ecaf6e699aaeab96f6d286f",
      "system":"linux_armv7l",
      "url":"http://repo.artik.cloud/artik/bin/pub/platformio/framework-artik-sdk-1.0.2.tar.gz",
      "version":"1.0.2"
    },
    {  
      "sha1":".........",
      "system":"linux_armv7l",
      "url":"http://repo.artik.cloud/artik/bin/pub/platformio/framework-artik-sdk-1.0.N.tar.gz",
      "version":"1.0.N"
    }
  ]
}
```

**Comment by glemercier** [comment]
Yep, rookie mistake. Just updated it.

**Comment by glemercier** [comment]
It looks good to me now and working as expected. If that's ok on your end I guess you can make a release. thanks.

**Comment by ivankravets** [comment]
1.2.0 is out! Thanks!

**Pull request merged**
